### ISSUE TITLE
[Question] Removing Intellij-Generated File

### ISSUE THREAD

**Issue by rayandrew** [Ditlog-Dev/ditlog-android#2]
It seems that folder .idea that intellij generated is pushed.

Is it better to not include intellij-generated file in the git?

For better stability between contributor.

Thank you :smile:

**Comment by keychera** [comment]
For an android project, some of the .idea files are needed to be included, and it was automatically not ignored by android studio

As stated here https://stackoverflow.com/questions/26336709/android-studio-should-the-entire-idea-directory-be-in-git-ignore

Since we all use the same android studio, I think it's fine to make this project IDE dependent

**Comment by rayandrew** [comment]
But we are using gradle for dependency management.
And i already see the content of .idea directory, and nothing is wrong to ignore it when pushing because it is just the same content with usual Intellij Idea and no dependency to Android. 
if you want to generate the new android studio project from this branch, just use Intellij/Android Studio to load gradle project like Android Fundamentals did.

This must be done so there's no additional commit for fixing and changing path to be relative like @evansp2612 did in Windows.

Also .vscode must be ignored to because it's just user's configuration

**Comment by keychera** [comment]
Well the answer in that SO do say we can ignore .idea folder in its entirety if we use gradle... 

I was under the impression that some of the files there is somehow needed but it seems that is not the case

I'll try fixing that later

**Comment by deryrahman** [comment]
Also .vscode, maybe you should review all code commited before merging into branch master. All we have on branch master is must clean. @keychera 

Yes, if you're using gradle, you can ignore .idea folder

> If you **do not use** something like Maven or Gradle to manage dependencies and build : **keep the directory under version control**.
> If you **do use** something like Maven or Gradle : correctly configure these tools and **do not keep the directory under version control**.
